In [1]:
import numpy as np

In [4]:
arr = np.linspace(1,10,10, dtype="int8")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [7]:
cond_index = arr > 5
cond_index

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [8]:
arr[cond_index]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [9]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [13]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [14]:
arr[arr > 5] = 99

In [15]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)