In [1]:
import numpy as np

In [4]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [6]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [7]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
matrix.ndim

[[1 2 3]
 [4 5 6]]


2

In [15]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]], [[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

## Add or delete dimensions

In [17]:
vector = np.array([1,2,3], ndmin=10)
print(vector)

[[[[[[[[[[1 2 3]]]]]]]]]]


In [18]:
expand = np.expand_dims([1,2,3], axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [21]:
print(vector, vector.ndim)
vector2 = np.squeeze(vector)
print(vector2)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3]
