In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int32')

In [6]:
arr = np.array([0,1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [7]:
arr

array([0., 1., 2., 3., 4.])

In [8]:
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [9]:
arr = arr.astype(np.string_)
arr

array([b'False', b'True', b'True', b'True', b'True'], dtype='|S5')

In [11]:
arr = np.array(["0", "1", "2", "3", "4"])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)