In [1]:
impo,10rt numpy as np

In [2]:
my_list = [1,2]
2*my_list

[1, 2, 1, 2]

In [5]:
arr = np.arange(0,10)
arr2 = arr.copy()

In [6]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
1/arr

C:\Users\Jesús de la Cueva\AppData\Local\Temp\ipykernel_1496\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [9]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [11]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
matrix = arr.reshape(2,5)
matrix2 = matrix.copy()

In [15]:
matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
matrix + matrix2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [19]:
matrix - matrix2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
np.matmul(matrix, matrix2.T)

array([[ 30,  80],
       [ 80, 255]])

In [21]:
matrix @ matrix2.T

array([[ 30,  80],
       [ 80, 255]])